rerun-triggers: "mtime"
cluster-cancel: "scancel"
restart-times: "0"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "5"
use-conda: "False"
use-singularity: "False"
use-envmodules: "True"
jobs: "500"
printshellcmds: "True"
slurm: "True"
keep-going: "True"
rerun-incomplete: "True"
envvars: ["SNIC_TMP"]
nolock: "True"
reason: "True"