$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
  sample_list:
    type: string
    description: path to a sample sheet
    default: "samples.csv"
  mag:
    type: object
    default:
      revision: "2.2.1"
      profile: [ "docker" ]
      resume: True
      config: ""
      assemblers: ["MEGAHIT"]
    properties:
      revision:
        type: string
        default: "2.2.1"
        description: "Revision of mag pipeline to use"
      profile:
        type: array
        default: ["docker"]
        description: "Profiles to use"
      resume:
        type: boolean
        default: True
        description: "Resume workflow"
      config:
        type: string
        default: ""
        description: "Path to nextflow style config file"
      assemblers:
        type: array
        default: ["MEGAHIT"]
        description: "What assemblers to use"
        items:
          enum: ["MEGAHIT", "SPAdes"]
  eggnog:
    type: object
    default:
      usemem: True
      eggnog_data_dir: "resources/eggNOG/5.0"
    properties:
      dbmem:
        type: boolean
        description: "Should the eggnog-mapper database be loaded into memory"
        default: True
      eggnog_data_dir:
        type: string
        description: "Path to the eggnog database directory"
        default: "resources/eggNOG/5.0"

  required:
    - sample_list
